// ================== PATIENT/USER ====================
// Sign Up - Patient User
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST'; 
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'; 
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'; 

// Log-in - Patient User
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'; 
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'; 
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'; 

// Log-out - Patient User
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'; 
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'; 
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'; 



// =================== PHYSICIAN ======================
// Sign Up - Physician 
export const SIGNUP_PHYSICIAN_REQUEST = 'SIGNUP_PHYSICIAN_REQUEST'; 
export const SIGNUP_PHYSICIAN_SUCCESS = 'SIGNUP_PHYSICIAN_SUCCESS'; 
export const SIGNUP_PHYSICIAN_FAILURE = 'SIGNUP_PHYSICIAN_FAILURE'; 

// Log-in - Physician
export const LOGIN_PHYSICIAN_REQUEST = 'LOGIN_PHYSICIAN_REQUEST'; 
export const LOGIN_PHYSICIAN_SUCCESS = 'LOGIN_PHYSICIAN_SUCCESS'; 
export const LOGIN_PHYSICIAN_FAILURE = 'LOGIN_PHYSICIAN_FAILURE'; 

// Log-OUT - Physician
export const LOGOUT_PHYSICIAN_REQUEST = 'LOGOUT_PHYSICIAN_REQUEST'; 
export const LOGOUT_PHYSICIAN_SUCCESS = 'LOGOUT_PHYSICIAN_SUCCESS'; 
export const LOGOUT_PHYSICIAN_FAILURE = 'LOGOUT_PHYSICIAN_FAILURE'; 